name: flutter_to_ride
description: "A simple, yet elegant Ticket to Ride companion app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  get_it: ^8.0.3
  get_storage: ^2.1.1
  intl: ^0.20.2
  pwa_install: ^0.0.6
  timeago: ^3.7.1
  uuid: ^4.5.1
  watch_it: ^1.6.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: 'RobotoSlab'
      fonts:
        - asset: 'fonts/RobotoSlab-ExtraLight.ttf'
          weight: 200
        - asset: 'fonts/RobotoSlab-Light.ttf'
          weight: 300
        - asset: 'fonts/RobotoSlab-Regular.ttf'
          weight: 400
        - asset: 'fonts/RobotoSlab-Medium.ttf'
          weight: 500
        - asset: 'fonts/RobotoSlab-SemiBold.ttf'
          weight: 600
        - asset: 'fonts/RobotoSlab-Bold.ttf'
          weight: 700
        - asset: 'fonts/RobotoSlab-ExtraBold.ttf'
          weight: 800
        - asset: 'fonts/RobotoSlab-Black.ttf'
          weight: 900
